DROP TABLE IF EXISTS votes
CASCADE;

CREATE TABLE votes
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  user_image_id INTEGER REFERENCES user_images(id) ON DELETE CASCADE
);